/**
 * ANIME BLOOM - MANUAL CONFIGURATION
 * Generated by AnimeBloom Admin Panel
 */

const heroSliderIds = [
    "daemons-of-the-shadow-realm-season-1-hindi-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "grand-blue-dreaming-season-1-hindi-dubbed",
    "scum-of-the-brave-season-1-hindi-dubbed",
    "there-was-a-cute-girl-in-the-heros-party-season-1-hindi-dubbed",
    "agents-of-the-four-seasons-dance-of-spring-season-1-hindi-dubbed",
    "nippon-sangoku-the-three-nations-of-the-crimson-sun-season-1-hindi-dubbed"
];

const newlyAddedIds = [
    "scum-of-the-brave-season-1-hindi-dubbed",
    "there-was-a-cute-girl-in-the-heros-party-season-1-hindi-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "wistoria-wand-and-sword-season-1-hindi-dubbed",
    "naruto-shippuden-season-1-hindi-dubbed",
    "bleach-season-1-hindi-dubbed",
    "kunon-the-sorcerer-can-see-season-1-hindi-dubbed",
    "nippon-sangoku-the-three-nations-of-the-crimson-sun-season-1-hindi-dubbed",
    "bofuri-i-dont-want-to-get-hurt-so-ill-max-out-my-defense-season-2-hindi-dubbed"
];

const recommendedIds = [
    "jujutsu-kaisen-season-3-hindi-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "sentenced-to-be-hero-season-1-hindi-dubbed",
    "daemons-of-the-shadow-realm-season-1-hindi-dubbed",
    "the-ramparts-of-ice-season-1-hindi-dubbed",
    "grand-blue-dreaming-season-1-hindi-dubbed",
    "classroom-of-the-elite-season-3-hindi-dubbed"
];

const trendingIds = [
    "jujutsu-kaisen-season-3-hindi-dubbed",
    "sentenced-to-be-hero-season-1-hindi-dubbed",
    "fire-force-season-3-hindi-dubbed",
    "frieren-beyond-journeys-end-season-2-hindi-dubbed",
    "trigun-stargaze-season-1-hindi-dubbed",
    "hells-paradise-season-2-english-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "the-ramparts-of-ice-season-1-hindi-dubbed",
    "grand-blue-dreaming-season-1-hindi-dubbed"
];

const movieIds = [];
const actionIds = [];
const comedyIds = [];
const isekaiIds = [];
const fantasyIds = [];
const adventureIds = [];
const romanceIds = [];