/**
 * ANIME BLOOM - MANUAL CONFIGURATION
 * Generated by AnimeBloom Admin Panel
 */

const heroSliderIds = [
    "the-angel-next-door-spoils-me-rotten-season-2-hindi-dubbed",
    "dorohedoro-season-1-hindi-dubbed",
    "the-beginning-after-the-end-season-2-hindi-dubbed",
    "daemons-of-the-shadow-realm-season-1-hindi-dubbed",
    "witch-hat-atelier-season-1-hindi-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "scum-of-the-brave-season-1-hindi-dubbed",
    "agents-of-the-four-seasons-dance-of-spring-season-1-hindi-dubbed",
    "nippon-sangoku-the-three-nations-of-the-crimson-sun-season-1-hindi-dubbed"
];

const newlyAddedIds = [
    "reborn-as-a-vending-machine-i-now-wander-the-dungeon-season-3-hindi-dubbed",
    "witch-hat-atelier-season-1-hindi-dubbed",
    "grand-blue-dreaming-season-1-hindi-dubbed",
    "easygoing-territory-defense-by-the-optimistic-lord-season-1-hindi-dubbed",
    "rezero-starting-life-in-another-world-season-2-hindi-dubbed",
    "eren-the-southpaw-season-1-hindi-dubbed",
    "marriagetoxin-season-1-hindi-dubbed",
    "rezero-starting-life-in-another-world-season-1-hindi-dubbed",
    "release-that-witch-season-1-hindi-dubbed"
];

const recommendedIds = [
    "jujutsu-kaisen-season-3-hindi-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "sentenced-to-be-hero-season-1-hindi-dubbed",
    "daemons-of-the-shadow-realm-season-1-hindi-dubbed",
    "the-ramparts-of-ice-season-1-hindi-dubbed",
    "grand-blue-dreaming-season-1-hindi-dubbed",
    "classroom-of-the-elite-season-3-hindi-dubbed"
];

const trendingIds = [
    "jujutsu-kaisen-season-3-hindi-dubbed",
    "sentenced-to-be-hero-season-1-hindi-dubbed",
    "fire-force-season-3-hindi-dubbed",
    "frieren-beyond-journeys-end-season-2-hindi-dubbed",
    "trigun-stargaze-season-1-hindi-dubbed",
    "hells-paradise-season-2-english-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "the-ramparts-of-ice-season-1-hindi-dubbed",
    "grand-blue-dreaming-season-1-hindi-dubbed"
];

const movieIds = [];
const actionIds = [];
const comedyIds = [];
const isekaiIds = [];
const fantasyIds = [];
const adventureIds = [];
const romanceIds = [];