/**
 * ANIME BLOOM - MANUAL CONFIGURATION
 * Generated by AnimeBloom Admin Panel
 */

const heroSliderIds = [
    "the-angel-next-door-spoils-me-rotten-season-2-hindi-dubbed",
    "dorohedoro-season-1-hindi-dubbed",
    "the-beginning-after-the-end-season-2-hindi-dubbed",
    "daemons-of-the-shadow-realm-season-1-hindi-dubbed",
    "witch-hat-atelier-season-1-hindi-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "scum-of-the-brave-season-1-hindi-dubbed",
    "agents-of-the-four-seasons-dance-of-spring-season-1-hindi-dubbed",
    "nippon-sangoku-the-three-nations-of-the-crimson-sun-season-1-hindi-dubbed"
];

const newlyAddedIds = [
    "snowball-earth-season-1-hindi-dubbed",
    "the-angel-next-door-spoils-me-rotten-season-2-hindi-dubbed",
    "an-observation-log-of-my-fiancee-who-calls-herself-a-villainess-season-1-hindi-dubbed",
    "death-note-season-1-hindi-dubbed",
    "chainsaw-man-the-movie-reze-arc-hindi-dubbed",
    "the-ramparts-of-ice-season-1-hindi-dubbed",
    "the-warrior-princess-and-the-barbaric-king-season-1-hindi-dubbed",
    "dr-stone-season-4-hindi-dubbed",
    "dorohedoro-season-1-hindi-dubbed"
];

const recommendedIds = [
    "the-angel-next-door-spoils-me-rotten-season-2-hindi-dubbed",
    "the-warrior-princess-and-the-barbaric-king-season-1-hindi-dubbed",
    "rezero-starting-life-in-another-world-season-2-hindi-dubbed",
    "eren-the-southpaw-season-1-hindi-dubbed",
    "marriagetoxin-season-1-hindi-dubbed",
    "rezero-starting-life-in-another-world-season-1-hindi-dubbed",
    "liar-game-season-1-hindi-dubbed",
    "snowball-earth-season-1-hindi-dubbed",
    "witch-hat-atelier-season-1-hindi-dubbed",
    "the-beginning-after-the-end-season-2-hindi-dubbed"
];

const trendingIds = [
    "jujutsu-kaisen-season-3-hindi-dubbed",
    "sentenced-to-be-hero-season-1-hindi-dubbed",
    "fire-force-season-3-hindi-dubbed",
    "frieren-beyond-journeys-end-season-2-hindi-dubbed",
    "trigun-stargaze-season-1-hindi-dubbed",
    "hells-paradise-season-2-english-dubbed",
    "release-that-witch-season-1-hindi-dubbed",
    "the-ramparts-of-ice-season-1-hindi-dubbed",
    "grand-blue-dreaming-season-1-hindi-dubbed"
];

const movieIds = [];
const actionIds = [];
const comedyIds = [];
const isekaiIds = [];
const fantasyIds = [];
const adventureIds = [];
const romanceIds = [];